# Generated by Django 2.0.5 on 2018-05-27 15:35
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length')
    ]

    operations = [
        CreateExtension('postgis'),
    ]
