# Generated by Django 2.0.5 on 2018-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_outlet_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='type',
            new_name='ctype',
        ),
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
