# Generated by Django 2.0.5 on 2018-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_user_atype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
