# Generated by Django 2.0.5 on 2018-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_auto_20180528_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
