# Generated by Django 2.0.5 on 2018-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_auto_20180531_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='outlets',
            field=models.ManyToManyField(related_name='coupons', related_query_name='coupon', to='main.Outlet'),
        ),
    ]
