# Generated by Django 2.0.5 on 2018-06-03 16:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_coupon_outlets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns',
                                    related_query_name='campaign', to='main.Organization'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons',
                                    related_query_name='coupon', to='main.Campaign'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons',
                                    related_query_name='coupon', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons',
                                    related_query_name='coupon', to='main.Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization',
                                       related_query_name='organization', to='main.Vendor'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets',
                                    related_query_name='outlet', to='main.Organization'),
        ),
    ]
