# Generated by Django 2.0.5 on 2018-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_auto_20180603_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
